version: '3'

networks: 
  laravel:

services: 
  db:
    image: mysql:8.0
    restart: always
    ports:
        - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=123
        - MYSQL_DATABASE=laravel
    command: --default-authentication-plugin=mysql_native_password --mysqlx=0
    cap_add:
        - SYS_NICE
    security_opt:
        - seccomp:unconfined

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: example_phpmyadmin
    ports:
        - 9999:80
    environment:
        - PMA_ARBITRARY=1
  web: 
    build: .
    command: '/app/run.sh'
    volumes: 
      - .:/app
    ports: 
      - "8000:8000"


